    name: Test

    on: [push]

    jobs:
      build:
        name: Test Run
        runs-on: ubuntu-latest
        
        # https://docs.github.com/en/free-pro-team@latest/actions/guides/creating-postgresql-service-containers#introduction
        # Service containers to run with `build`
        services:
          # Label used to access the service container
          postgres:
            # Docker Hub image
            # https://hub.docker.com/_/postgres
            image: postgres
            env:
              POSTGRES_PASSWORD: postgres
            # Set health checks to wait until postgres has started
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              - 5432:5432


        steps:
          - name: createdb test
            run: createdb testtesttest
            env:
              PGPASSWORD: postgres
          - name: Checkout repo code
            uses: actions/checkout@v2
          - name: Install dependencies
            run: npm ci
          - run: npm test