    name: Test

    on: [push]

    jobs:
      build:
        name: Test Run
        runs-on: ubuntu-latest
        
        # https://docs.github.com/en/free-pro-team@latest/actions/guides/creating-postgresql-service-containers#introduction
        # Service containers to run with `build`
        services:
          # Label used to access the service container
          postgres:
            # Docker Hub image
            # https://hub.docker.com/_/postgres
            image: postgres
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
            # Set health checks to wait until postgres has started
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5


        steps:
          - uses: actions/checkout@v2
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}
          - run: npm ci
          - run: npm test
            env:
              # See https://www.postgresql.org/docs/9.1/libpq-envars.html
              PGHOST: postgres
              PGPORT: 5432
              PGUSER: postgres
              PGPASSWORD: postgres